from .styles import Styles
from .base_components import CelldetectiveWidget, CelldetectiveMainWindow
from .json_readers import ConfigEditor
from .tableUI import TableUI
from celldetective.gui.settings._settings_neighborhood import ConfigNeighborhoods
from .classifier_widget import ClassifierWidget
from .survival_ui import ConfigSurvival
from .plot_signals_ui import ConfigSignalPlot
from celldetective.gui.settings._settings_signal_annotator import SettingsSignalAnnotator
from .signal_annotator import SignalAnnotator
from .signal_annotator2 import SignalAnnotator2
from celldetective.gui.settings._settings_event_model_training import SettingsEventDetectionModelTraining
from celldetective.gui.settings._settings_segmentation_model_training import SettingsSegmentationModelTraining
from .thresholds_gui import ThresholdConfigWizard
from .seg_model_loader import SegmentationModelLoader
from .process_block import ProcessPanel, NeighPanel, PreprocessingPanel
from .analyze_block import AnalysisPanel
from .control_panel import ControlPanel
from .configure_new_exp import ConfigNewExperiment
