[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "celldetective"
authors = [{name = "Rémy Torro", email = "remy.torro@inserm.fr"}]
dynamic = ["version", "description"]
